# General config for each StellarPlugin

# The cooldown time for each arena to start when the arena have the min players
Cooldown: 10
# Choose if the arenas have a wait lobby or not
Wait_Lobby: true


# The language that the plugin uses, if the language is not found, it will use the default language
# The avalibles languages are: en_US, es_ES
Lang: "en_US"
# The debug mode of the plugin, if it is enabled, it will show all the debug messages in the console
Debug_Mode: false
# The metrics of the plugin, if it is enabled, it will send the metrics to bStats
BStats_Metrics: false


# Config version - DO NOT CHANGE IT!
Config_Version: 1.0